keys:
  age:
    - &framework age102w4y6gsntvw93n590agqdg9v3tt8rs0x2kpunvu39jh6lyvdpeq7ct844
    - &macbook age1cfd003wlk8w2hhtlwflyuc6lzwsswc48kpl9cafrg4kc5jp3u5rqckcf5l
    - &bachtel age1z9ka8nm4v5rrgxr72n3mmxdtlq4l468rhn7sn57kj2qtd96rff8qqqlzap
    - &halti age1rv2srjksxsqc5kgyvq8axr9pwvsg3m8d07q379ntxjqz2s2gu5pssts9h9
    - &lagern age1erlqclg0xwmyxj339akx2xeaq3crapxcd2qr7z2hjy5q8v59aqfq2qx3tu
    - &odake age16urcveanputmn5vrt579xnk2pk87mlv0d2fmwzn2059qtzklmq9smj34a5
    - &walberla age1s3syz6jhdj9qqz4lcu42uxckpn8na56qa3sehuy6cpwtypf3349qkjry6v
creation_rules:
  - path_regex: .*
    key_groups:
      - age:
          - *framework
          - *macbook
          - *bachtel
          - *halti
          - *lagern
          - *odake
          - *walberla
