[general]
home = "~/Workspace"
concurrency = 1
[general.env]
"GIT_SSH_COMMAND" = "ssh -o TcpKeepAlive=no -o ServerAliveInterval=10"

[platform.github]
origin = true
domain = "github.com"
user = "stepbrobd"

[platform.sourcehut]
origin = false
domain = "git.sr.ht"
user = "~stepbrobd"

## Personal
[repo.".soft-serve"]
description = "soft serve configs"

[repo."aoc"]
description = "advent of code"

[repo."churn"]
description = "churn, baby, churn!"

[repo."consistency-coq"]
description = "consistency semantics with coq"

[repo."consistency-z3"]
description = "consistency semantics with z3"

[repo."cv"]
description = "cv in typst with auto build and release"

[repo."dotfiles"]
description = "yet another dotfiles repo with nix"

[repo."finch"]
description = "hackzurich 2023: finch - a simple neural net framework and visualizer that uses genetic networks to train"

[repo."metaprocessor"]
description = "metaprocessor, all-in-one data pipeline for mbientlab metawear series sensors"

[repo."nixology"]
nixology = "all about nix"

[repo."sentik"]
description = "hackmit 2022: sentik - live tweet sentiment analysis for traders"

[repo."srd"]
description = "srd: (go) static race detector"

[repo."stepbrobd"]
description = "just another profile readme"

[repo."tailscale-acls"]
description = "tailscale access controls"

[repo."tailscale-on-fly.io"]
description = "run a vpn service with global exit nodes with fly.io and tailscale"

[repo."tailscale-on-openwrt"]
description = "brings tailscale to low powered openwrt devices"

[repo."ysun"]
description = "nix + deno + fresh"

## Forks
[repo."crunchycli"]
description = "forked from crunchy-labs/crunchy-cli"

[repo."deno2nix"]
description = "forked from sno2wman/deno2nix"

[repo."go"]
description = "forked from golang/go"

[repo."hopper"]
description = "forked from cybergenik/hopper"

[repo."nix"]
description = "forked from nixos/nix"

[repo."nixpkgs"]
description = "forked from nixos/nixpkgs"

[repo."soft-serve"]
description = "forked from charmbracelet/soft-serve"

[repo."tailscale"]
description = "forked from tailscale/tailscale"

## Northeastern University
[repo."neu-cs-5010"]
description = "cs 5010 fall 2023 @ northeastern university"

[repo."neu-cs-5200"]
description = "cs 5200 spring 2024 @ northeastern university"

[repo."neu-cs-5800"]
description = "cs 5800 fall 2023 @ northeastern university"

[repo."neu-cy-6740"]
description = "cy 6740 spring 2024 @ northeastern university"

## University of Utah
[repo."uutah-cs-1410"]
description = "cs 1410 spring 2020 @ university of utah"
archived = true

[repo."uutah-cs-2420"]
description = "cs 2420 fall 2020 @ university of utah"
archived = true

[repo."uutah-cs-3011"]
description = "cs 3011 spring 2023 @ university of utah"
archived = true

[repo."uutah-cs-3500"]
description = "cs 3500 spring 2021 @ university of utah"
archived = true

[repo."uutah-cs-3505"]
description = "cs 3505 fall 2021 @ university of utah"
archived = true

[repo."uutah-cs-4150"]
description = "cs 4150 spring 2022 @ university of utah"
archived = true

[repo."uutah-cs-4400"]
description = "cs 4400 fall 2021 @ university of utah"
archived = true

[repo."uutah-cs-4440"]
description = "cs 4440 spring 2022 @ university of utah"
archived = true

[repo."uutah-cs-4480"]
description = "cs 4480 spring 2022 @ university of utah"
archived = true

[repo."uutah-cs-4790"]
description = "cs 4790 spring 2023 @ university of utah"
archived = true

[repo."uutah-cs-6110"]
description = "cs 6110 spring 2023 @ university of utah"
archived = true

[repo."uutah-cs-6340"]
description = "cs 6340 fall 2022 @ university of utah"
archived = true

[repo."uutah-cs-6450"]
description = "cs 6450 fall 2022 @ university of utah"
archived = true

[repo."uutah-cs-6490"]
description = "cs 6490 spring 2023 @ university of utah"
archived = true
