# General
[general]
home = "~/Workspace"

# StepBroBD
[platform.stepbrobd]
origin = false
public = "https://git.stepbrobd.com/stepbrobd"
private = "git@git.stepbrobd.com:stepbrobd"

# GitHub
[platform.github]
origin = true
public = "https://github.com/stepbrobd"
private = "git@github.com:stepbrobd"

# SourceHut
[platform.sourcehut]
origin = false
public = "https://git.sr.ht/~stepbrobd"
private = "git@git.sr.ht:~stepbrobd"

# Dotfiles
[repo."dotfiles"]

# Nix
[repo."nix"]
[repo."nixpkgs"]
[repo."nur"]
[repo."osu-overlay"]
[repo."raycast-overlay"]
[repo."vscode-overlay"]

# Personal
[repo."betaenrollmentdata.plist"]
[repo."cv"]
[repo."metaprocessor"]
[repo."repos"]
[repo."srd"]
[repo."stepbrobd"]
[repo."tailscale-acls"]

# Sites
[repo."git.stepbrobd.com"]
[repo."sentik.xyz"]
[repo."stepbrobd.com"]
[repo."viral.vision"]
[repo."xdg.sh"]
[repo."ysun.co"]

# Forks
[repo."crunchycli"]
[repo."go"]
[repo."hopper"]
[repo."soft-serve"]
[repo."tailscale"]
[repo."tailscale-on-fly.io"]
[repo."tailscale-on-openwrt"]
[repo."turbo"]
[repo."tmux-power"]

# University of Utah
[repo."uutah-cs-1410"]
[repo."uutah-cs-2420"]
[repo."uutah-cs-3011"]
[repo."uutah-cs-3500"]
[repo."uutah-cs-3505"]
[repo."uutah-cs-4150"]
[repo."uutah-cs-4400"]
[repo."uutah-cs-4440"]
[repo."uutah-cs-4480"]
[repo."uutah-cs-4790"]
[repo."uutah-cs-6110"]
[repo."uutah-cs-6340"]
[repo."uutah-cs-6450"]
[repo."uutah-cs-6490"]

