name: "Discord"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  Discord:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        name: "Checkout"
        with:
          fetch-depth: 0
      - name: "Install Nix"
        uses: "cachix/install-nix-action@v23"
      - name: "Magic Cache"
        uses: "determinatesystems/magic-nix-cache-action@v2"
      - name: "Discord"
        run: |
          ./scripts/mkdiscordhook.sh
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
          TOKEN: ${{ secrets.TOKEN }}
          WEBHOOK: ${{ secrets.WEBHOOK }}
