name: "Sync"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  Sync:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        name: "Checkout"
        with:
          fetch-depth: 0
      - name: "Install Nix"
        uses: "cachix/install-nix-action@V27"
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: "Magic Cache"
        uses: "determinatesystems/magic-nix-cache-action@v7"
      - name: "Sync"
        run: nix run --accept-flake-config .#stepbrobd -- sync
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
          TOKEN: ${{ secrets.TOKEN }}
