name: "Update"

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  Webhook:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        name: "Checkout"
        with:
          fetch-depth: 0
      - name: "Webhook"
        run: |
          bash ./scripts/webhook.sh
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
          TOKEN: ${{ secrets.TOKEN }}
          WEBHOOK: ${{ secrets.WEBHOOK }}

  Update:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        name: "Checkout"
        with:
          fetch-depth: 0
      - name: "Install Nix"
        uses: "cachix/install-nix-action@v22"
      - name: "Magic Cache"
        uses: "determinatesystems/magic-nix-cache-action@v2"
      - name: "Update"
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          nix flake update --commit-lock-file
          git push
